// <auto-generated />
using System;
using HelloWorldApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorldApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("HelloWorldApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HelloWorldApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("postedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("sellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Textbooks",
                            Description = "A comprehensive textbook covering all aspects of organic chemistry, including reaction mechanisms, synthesis, and spectroscopy.",
                            ImageUrl = "https://example.com/images/organic-chemistry-textbook.jpg",
                            Price = 19.99m,
                            Title = "Organic Chemistry Textbook",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Audrey Smith"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Clothing",
                            Description = "Official Ohio State University game day jersey featuring the school's colors and logo.",
                            ImageUrl = "https://example.com/images/osu-game-day-jersey.jpg",
                            Price = 14.99m,
                            Title = "OSU Game Day Jersey",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Brian Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Stationery",
                            Description = "A set of 10 mechanical pencils with different lead thicknesses, perfect for students and professionals.",
                            ImageUrl = "https://example.com/images/mechanical-pencil-set.jpg",
                            Price = 9.99m,
                            Title = "Mechanical Pencil Set",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Catherine Lee"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dorm Decor",
                            Description = "A bright and energy-efficient desktop lamp with adjustable brightness.",
                            ImageUrl = "https://example.com/images/desktop-lamp.jpg",
                            Price = 29.99m,
                            Title = "Desktop Lamp",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Alyssa Powell"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Dorm Decor",
                            Description = "A set of 10 LED light strips with adjustable brightness and color options.",
                            ImageUrl = "https://example.com/images/led-light-strip.jpg",
                            Price = 39.99m,
                            Title = "LED Light Strip",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "David Martinez"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Stationery",
                            Description = "A set of 12 highlighters in various colors for marking important text.",
                            ImageUrl = "https://example.com/images/highlighter-set.jpg",
                            Price = 12.99m,
                            Title = "Highlighter Set",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Emily Davis"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothing",
                            Description = "A comfortable Ohio State University hoodie featuring the school's logo and colors.",
                            ImageUrl = "https://example.com/images/osu-hoodie.jpg",
                            Price = 34.99m,
                            Title = "OSU Hoodie",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Michael Brown"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Textbooks",
                            Description = "A comprehensive textbook covering advanced calculus topics for students in Calculus II.",
                            ImageUrl = "https://example.com/images/calculus-ii-textbook.jpg",
                            Price = 35.00m,
                            Title = "Calculus II Textbook",
                            postedDate = new DateOnly(2026, 4, 1),
                            sellerName = "Sarah Wilson"
                        });
                });

            modelBuilder.Entity("HelloWorldApi.Models.CartItem", b =>
                {
                    b.HasOne("HelloWorldApi.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloWorldApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HelloWorldApi.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
